alias pU="trizen -Syu"
alias pR="sudo pacman -Rns"
alias pO="sudo pacman -Rns $(pacman -Qtdq)"
alias pS="trizen -S"
alias pSs="trizen -Ss"
alias K="sudo killall"
alias fuck='sudo $(fc -nl -1)'
alias cls="clear"
alias snano="sudo nano"
alias pMesa="pS mesa libdrm lib32-mesa lib32-libdrm xf86-video-ati opencl-mesa lib32-mesa-vdpau lib32-llvm-libs llvm-libs libclc clang compiler-rt lib32-vulkan-intel  lib32-vulkan-radeon vulkan-intel vulkan-mesa-layer vulkan-radeon amdvlk lib32-amdvlk"

bindkey "\033[1~" beginning-of-line
bindkey "\033[4~" end-of-line
eval $( dircolors -b $HOME/.dircolors ) 
